from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

old="""    const normalizeDni = value => String(value || \"\").replace(/\\D/g, \"\");\n    const normalizePhone = value => String(value || \"\").replace(/\\D/g, \"\");"""
new="""    const normalizeDni = value => String(value || \"\").replace(/\\D/g, \"\");\n    const normalizePhone = value => String(value || \"\").replace(/\\D/g, \"\");\n    const customerWhatsappUrl = rawPhone => {\n        let phone = normalizePhone(rawPhone);\n        if (!phone) return '';\n        if (phone.startsWith('0')) phone = phone.replace(/^0+/, '');\n        if (phone.startsWith('15') && phone.length <= 10) phone = phone.slice(2);\n        if (!phone.startsWith('54')) phone = '54' + phone;\n        if (phone.startsWith('54') && !phone.startsWith('549')) phone = '549' + phone.slice(2);\n        return `https://api.whatsapp.com/send?phone=${phone}&text=${encodeURIComponent('Hola! Te escribo de lucasabraham.ph por el canje que realizaste en el Club de beneficios para coordinar la entrega.')}`;\n    };"""
if old not in s: raise SystemExit('normalize marker not found')
s=s.replace(old,new,1)

old2="""                            (matchedOrder.type === 'benefit_redemption' || matchedOrder.benefitRedemption === true) && React.createElement(\"div\", { className:\"club-order-badge mt-2\" }, React.createElement(\"i\", { className:\"fas fa-gift\" }), `CANJE CLUB · ${matchedOrder.rewardName || 'Beneficio'} · -${matchedOrder.redeemedPoints || 0} puntos`),\n                            matchedOrder.printRequested && React.createElement(\"div\", { className:\"print-order-badge mt-2\" }, React.createElement(\"i\", { className:\"fas fa-print\" }), `IMPRESIÓN 10x15 · ${Number(matchedOrder.printCount) || (matchedOrder.printedItems || []).length || 1} foto${(Number(matchedOrder.printCount) || (matchedOrder.printedItems || []).length || 1) === 1 ? '' : 's'}`)),"""
new2="""                            (matchedOrder.type === 'benefit_redemption' || matchedOrder.benefitRedemption === true) && React.createElement(React.Fragment, null,\n                                React.createElement(\"div\", { className:\"club-order-badge mt-2\" }, React.createElement(\"i\", { className:\"fas fa-gift\" }), `CANJE CLUB · ${matchedOrder.rewardName || 'Beneficio'} · -${matchedOrder.redeemedPoints || 0} puntos`),\n                                React.createElement(\"div\", { className:\"mt-4 rounded-2xl border border-emerald-500/25 bg-emerald-500/10 p-4\" },\n                                    React.createElement(\"p\", { className:\"text-[10px] uppercase tracking-[.18em] text-emerald-300 font-black mb-1\" }, \"ENTREGAR A\"),\n                                    React.createElement(\"div\", { className:\"text-2xl sm:text-3xl font-black text-white leading-tight\" }, matchedOrder.customerName || 'Sin nombre'),\n                                    React.createElement(\"div\", { className:\"mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-neutral-200\" },\n                                        React.createElement(\"span\", null, React.createElement(\"i\", { className:\"fas fa-id-card mr-2 text-emerald-300\" }), `DNI ${matchedOrder.dni || matchedOrder.customerDni || 'Sin DNI'}`),\n                                        React.createElement(\"span\", null, React.createElement(\"i\", { className:\"fas fa-phone mr-2 text-emerald-300\" }), matchedOrder.phone || matchedOrder.celular || 'Sin teléfono')),\n                                    customerWhatsappUrl(matchedOrder.phone || matchedOrder.celular) && React.createElement(\"button\", { type:\"button\", onClick:() => window.open(customerWhatsappUrl(matchedOrder.phone || matchedOrder.celular), '_blank'), className:\"mt-3 inline-flex items-center justify-center gap-2 bg-[#25D366] text-black px-4 py-3 rounded-xl font-black text-sm\" }, React.createElement(\"i\", { className:\"fab fa-whatsapp text-lg\" }), \"Hablar por WhatsApp para coordinar\"))),\n                            matchedOrder.printRequested && React.createElement(\"div\", { className:\"print-order-badge mt-2\" }, React.createElement(\"i\", { className:\"fas fa-print\" }), `IMPRESIÓN 10x15 · ${Number(matchedOrder.printCount) || (matchedOrder.printedItems || []).length || 1} foto${(Number(matchedOrder.printCount) || (matchedOrder.printedItems || []).length || 1) === 1 ? '' : 's'}`)),"""
if old2 not in s: raise SystemExit('detail marker not found')
s=s.replace(old2,new2,1)

old3="""                                        (o.type === 'benefit_redemption' || o.benefitRedemption === true) && React.createElement(\"span\", { className:\"club-order-badge\" }, \"CANJE CLUB\"),\n                                        o.printRequested && React.createElement(\"span\", { className:\"print-order-badge\" }, `10x15 × ${Number(o.printCount) || (o.printedItems || []).length || 1}`)),\n                                    React.createElement(OrderPreviewStrip, { items: o.items || [], limit: 4 }),"""
new3="""                                        (o.type === 'benefit_redemption' || o.benefitRedemption === true) && React.createElement(\"span\", { className:\"club-order-badge\" }, \"CANJE CLUB\"),\n                                        o.printRequested && React.createElement(\"span\", { className:\"print-order-badge\" }, `10x15 × ${Number(o.printCount) || (o.printedItems || []).length || 1}`)),\n                                    (o.type === 'benefit_redemption' || o.benefitRedemption === true) && React.createElement(\"div\", { className:\"mb-2\" },\n                                        React.createElement(\"p\", { className:\"text-lg font-black text-white\" }, o.customerName || 'Sin nombre'),\n                                        React.createElement(\"p\", { className:\"text-xs text-neutral-400\" }, `DNI ${o.dni || o.customerDni || 'Sin DNI'} · ${o.phone || o.celular || 'Sin teléfono'} · ${o.rewardName || 'Beneficio'}`)),\n                                    React.createElement(OrderPreviewStrip, { items: o.items || [], limit: 4 }),"""
if old3 not in s: raise SystemExit('queue marker not found')
s=s.replace(old3,new3,1)

if 'v77-club-rewards-3-and-5' in s:
    s=s.replace('v77-club-rewards-3-and-5','v78-redemption-contact')
elif 'v77-club-rewards-3-5' in s:
    s=s.replace('v77-club-rewards-3-5','v78-redemption-contact')
elif 'v76-club-gallery-points-reset' in s:
    s=s.replace('v76-club-gallery-points-reset','v78-redemption-contact')
else:
    raise SystemExit('version marker not found')
p.write_text(s,encoding='utf-8')
print('patched')
