from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
def between(a,b,repl):
 global s
 assert s.count(a)==1,(a,s.count(a))
 start=s.index(a);end=s.index(b,start+len(a));s=s[:start]+repl+'\n'+s[end:]
def once(a,b):
 global s
 assert s.count(a)==1,(a,s.count(a));s=s.replace(a,b,1)
core=Path('.github/scripts/order-storage-v102.js').read_text(encoding='utf-8')
core=core.replace("function localRead(){try{return JSON.parse(localStorage.getItem(fallback)||'[]')}catch(e){return []}}", "function localRead(){try{const v=JSON.parse(localStorage.getItem(fallback)||'[]');return Array.isArray(v)?v:[]}catch(e){return []}}")
Path('.github/scripts/order-storage-v102.js').write_text(core,encoding='utf-8')
between('async function saveOrderFirebase(order) {','async function loadOrdersFirebase(limit = 3000) {',core+'''\nconst LAOrderOutbox=LAOrderStorage.createOutbox();
const LA_ORDER_SAVE_INFLIGHT=new Map();
let LA_PENDING_SYNC_RUNNING=false;
function orderDeadline(promise,ms=45000){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('La conexión demoró demasiado. El pedido sigue pendiente.')),ms)})]).finally(()=>clearTimeout(timer))}
function newOrderCode(){const random=typeof crypto!=='undefined'&&crypto.getRandomValues?Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>n.toString(16).padStart(2,'0')).join(''):Math.random().toString(36).slice(2,14);return 'LA-'+Date.now().toString(36).toUpperCase()+'-'+random.toUpperCase()}
function safeOrderWhatsappUrl(pkg){if(pkg.whatsappUrl.length<=6000)return pkg.whatsappUrl;const text=`Hola Lucas! Te envío mi pedido ${pkg.order} de ${pkg.orderData.items.length} fotos por ${formatPrice(pkg.orderData.total)}. El detalle completo, incluidas las impresiones, está guardado en el Admin. A continuación te envío el comprobante.`;return `https://api.whatsapp.com/send?phone=${SELLER_PHONE}&text=${encodeURIComponent(text)}`}
async function saveOrderFirebase(order){const db=await getFirebaseDb();if(!db)throw new Error('Firebase no inicializó');const clean={...order,id:order.id||order.orderId||order.codigo||order.code};if(!clean.id)throw new Error('El pedido no tiene código');await LAOrderStorage.persist(db,ORDERS_COLLECTION_PATH,clean,firebaseDocId);window.LA_LAST_FIREBASE_SAVE={ok:true,id:clean.id,paths:[ORDERS_COLLECTION_PATH],at:new Date().toISOString(),appVersion:APP_VERSION};return true}
''')
between('async function loadOrdersFirebase(limit = 3000) {','function orderCodeVariants(v) {','''async function loadOrdersFirebase(limit=3000){const db=await getFirebaseDb();if(!db)throw new Error('Firebase no inicializó');const all=[],errors=[];let successful=0;for(const path of [...legacyOrderCollections(),ORDERS_COLLECTION_PATH]){const collection=db.collection(path),docs=new Map();for(const query of [collection.where('delivered','==',false),collection.orderBy('date','desc').limit(Math.max(300,Math.min(limit,1000)))]){try{const snap=await query.get({source:'server'});successful++;snap.docs.forEach(d=>docs.set(d.id,d))}catch(e){errors.push(String(e&&e.message||e))}}const entries=[...docs.values()];for(let i=0;i<entries.length;i+=6){const group=await Promise.all(entries.slice(i,i+6).map(async d=>{const data={id:d.data().id||d.id,...d.data()};try{return {...await LAOrderStorage.hydrate(d.ref,data),_firebasePath:path}}catch(e){console.warn('Detalle de pedido pendiente de recuperar:',data.id,e);return {...data,storageIncomplete:true,_firebasePath:path}}}));all.push(...group)}}window.LA_LAST_ORDER_FIREBASE_READ={ok:successful>0,errors,at:new Date().toISOString()};if(!successful)throw new Error(errors.join('; ')||'No se pudieron consultar pedidos en Firebase');return mergeOrders(all)}''')
between('async function findOrderEverywhere(code) {','async function updateOrderFirebase(orderId, partial) {','''async function findOrderEverywhere(code){const q=normalizeOrderCode(code);if(!q)return null;try{const db=await getFirebaseDb();if(db){for(const path of [ORDERS_COLLECTION_PATH,...legacyOrderCollections()]){for(const id of orderCodeVariants(q)){const found=await LAOrderStorage.read(db,path,id,firebaseDocId);if(found)return found}}}}catch(e){console.warn('Búsqueda directa Firebase:',e)}try{const r=await apiAction({action:'getOrder',orderId:q});if(r&&r.order&&sameOrderCode(r.order.id||r.order.orderId,q))return r.order}catch(e){}try{const hit=findOrderInList(await loadOrdersRemote(),q);if(hit)return hit}catch(e){}return findOrderInList(mergeOrders(readLocalOrders(),readPendingOrders(),await LAOrderOutbox.all()),q)}''')
between('async function syncPendingOrders() {','function compactOrderForScript(order) {','''async function syncPendingOrders(){if(LA_PENDING_SYNC_RUNNING)return;LA_PENDING_SYNC_RUNNING=true;try{const pending=mergeOrders(readPendingOrders(),await LAOrderOutbox.all());for(const order of pending){const result=await saveOrderRemote(order);if(!result.firebase&&!result.script)console.warn('Pedido conservado para reintento:',order.id,result.error)}}finally{LA_PENDING_SYNC_RUNNING=false}}
window.addEventListener('online',()=>syncPendingOrders().catch(e=>console.warn('Reintento de pedidos:',e)));
setTimeout(()=>syncPendingOrders().catch(e=>console.warn('Recuperación de pedidos:',e)),2000);
''')
between('async function saveOrderRemote(order) {','async function loadOrdersRemote() {','''async function saveOrderRemote(order){const clean={...order,id:order.id||order.orderId||order.codigo||order.code,date:order.date||new Date().toISOString(),items:Array.isArray(order.items)?order.items:[]};if(!clean.id)throw new Error('Falta el código del pedido');const key=normalizeOrderCode(clean.id);if(LA_ORDER_SAVE_INFLIGHT.has(key))return LA_ORDER_SAVE_INFLIGHT.get(key);const work=(async()=>{await LAOrderOutbox.put(clean);saveLocalOrders(mergeOrders([clean],readLocalOrders()));const status={firebase:false,script:false,error:'',id:clean.id};try{await orderDeadline(saveOrderFirebase(clean));status.firebase=true}catch(e){status.error=String(e&&e.message||e);console.warn('Firebase no confirmó el pedido:',clean.id,e)}if(!status.firebase){const compact=compactOrderForScript(clean),params={action:'createOrder',order:JSON.stringify(compact)},encoded=new URLSearchParams(params).toString();if(encoded.length<=7000){try{const response=await apiAction(params);if(!LAOrderStorage.verifiedAck(response,clean.id,normalizeOrderCode))throw new Error('El respaldo no confirmó el guardado');const verify=await apiAction({action:'getOrder',orderId:clean.id}),found=verify&&verify.order,count=found?(Array.isArray(found.items)?found.items.length:Number(found.itemCount)||0):0;if(!found||!sameOrderCode(found.id||found.orderId,clean.id)||count!==clean.items.length||Number(found.total)!==Number(clean.total))throw new Error('El respaldo no devolvió el pedido completo');status.script=true}catch(e){status.error=String(e&&e.message||e);console.warn('Apps Script no confirmó el pedido:',clean.id,e)}}else status.error='El respaldo alternativo no admite este tamaño; el pedido quedó conservado para reintentar Firebase.'}if(status.firebase||status.script){await LAOrderOutbox.remove(clean.id);savePendingOrders(readPendingOrders().filter(o=>!sameOrderCode(o.id,clean.id)))}else savePendingOrders(mergeOrders([compactOrderForScript(clean)],readPendingOrders()));window.LA_LAST_ORDER_SAVE_STATUS={...status,ordersPath:ORDERS_COLLECTION_PATH,at:new Date().toISOString(),appVersion:APP_VERSION};return status})().finally(()=>LA_ORDER_SAVE_INFLIGHT.delete(key));LA_ORDER_SAVE_INFLIGHT.set(key,work);return work}''')
between('async function loadOrdersRemote() {','async function markOrderDelivered(orderId, delivered) {','''async function loadOrdersRemote(){const [sr,fr]=await Promise.allSettled([apiAction({action:'listOrders'}),loadOrdersFirebase()]);const scriptOk=sr.status==='fulfilled'&&sr.value&&!sr.value.error&&sr.value.ok!==false&&Array.isArray(sr.value.orders),firebaseOk=fr.status==='fulfilled';const scriptOrders=scriptOk?sr.value.orders:[],firebaseOrders=firebaseOk?fr.value:[];window.LA_ORDER_LOAD_WARNING=!scriptOk&&!firebaseOk?'No se pudieron consultar los pedidos remotos. Se muestran los respaldos disponibles.':(!scriptOk||!firebaseOk?'Una fuente de pedidos no respondió. Revisá los pendientes si falta alguno.':'');const byId=new Map(scriptOrders.map(o=>[normalizeOrderCode(o.id||o.orderId||o.codigo||o.code),o]));const completeFirebase=firebaseOrders.map(o=>{if(!o.storageIncomplete)return o;const backup=byId.get(normalizeOrderCode(o.id));return backup&&Array.isArray(backup.items)&&backup.items.length===Number(o.itemCount)?{...o,items:backup.items,printedItems:backup.printedItems||[],printedPhotoIds:backup.printedPhotoIds||[],storageIncomplete:false}:o});const local=!scriptOk&&!firebaseOk?mergeOrders(readLocalOrders(),readPendingOrders(),await LAOrderOutbox.all()):[];return mergeOrders(local,scriptOrders,completeFirebase)}''')
once('    const [checkoutPointsLoading, setCheckoutPointsLoading] = useState(false);','    const [checkoutPointsLoading, setCheckoutPointsLoading] = useState(false);\n    const [checkoutSaving, setCheckoutSaving] = useState(false);\n    const [checkoutSaveError, setCheckoutSaveError] = useState("");\n    const orderSavingRef = useRef(false);')
once("        setCheckoutOrderCode('LA-' + Math.floor(10000 + Math.random() * 90000));", "        setCheckoutSaveError('');\n        setCheckoutOrderCode(newOrderCode());")
once("buildOrderPackage(checkoutOrderCode || ('LA-' + Math.floor(10000 + Math.random() * 90000))).whatsappUrl", "safeOrderWhatsappUrl(buildOrderPackage(checkoutOrderCode || newOrderCode()))")
between('    const sendOrder = async (e) => {','    const addClubProduct = () => {','''    const sendOrder=async(e)=>{if(e&&e.preventDefault)e.preventDefault();if(orderSavingRef.current)return;if(!cart.length||!selectedPhotos.length){alert('Seleccioná al menos una foto antes de comprar.');return}if(!String(checkoutCustomerName||'').trim()||!normalizePhone(checkoutPhone)){setCustomerDetailsOpen(true);alert('Antes de finalizar, guardá tu nombre y apellido y un celular de contacto.');return}if(checkoutPrint&&!printSelectedPhotos.length){alert('Elegí al menos una foto para imprimir o desactivá la impresión.');return}const fixedCode=checkoutOrderCode||newOrderCode();if(!checkoutOrderCode)setCheckoutOrderCode(fixedCode);const pkg=buildOrderPackage(fixedCode);orderSavingRef.current=true;setCheckoutSaving(true);setCheckoutSaveError('');try{const status=await saveOrderRemote(pkg.orderData);if(!status.firebase&&!status.script){const message=`No pudimos confirmar el pedido ${fixedCode}. Tus fotos siguen seleccionadas y el pedido quedó conservado para reintentar. ${status.error||''}`;setCheckoutSaveError(message);alert(message);return}const whatsappUrl=safeOrderWhatsappUrl(pkg);try{localStorage.setItem('LA_LAST_ORDER_RECEIPT',JSON.stringify({id:fixedCode,date:pkg.orderData.date,itemCount:pkg.orderData.items.length,total:pkg.orderData.total,whatsappUrl}));localStorage.removeItem('LA_RECOVER_CART')}catch(e){}setAdminMessage(`Pedido ${fixedCode} guardado correctamente.`);setCart([]);setCheckoutOpen(false);setAppliedCoupon(null);setCheckoutCoupon('');setCouponMessage('');setCheckoutPrint(false);setPrintedPhotoIds([]);window.location.href=whatsappUrl}catch(err){const message=`No se pudo conservar o confirmar el pedido ${fixedCode}. Tus fotos siguen seleccionadas. ${String(err&&err.message||err)}`;setCheckoutSaveError(message);alert(message)}finally{orderSavingRef.current=false;setCheckoutSaving(false)}};
''')
s=s.replace('checkoutOpen && React.createElement("button", { type:"button", onClick:sendOrder, disabled:!cart.length, className:"checkout-floating-cta" }','checkoutOpen && React.createElement("button", { type:"button", onClick:sendOrder, disabled:!cart.length||checkoutSaving, className:"checkout-floating-cta" }')
needle='        checkoutOpen && React.createElement("button", { type:"button", onClick:sendOrder, disabled:!cart.length||checkoutSaving, className:"checkout-floating-cta" }'
assert s.count(needle)==1
s=s.replace(needle,'''        checkoutOpen && checkoutSaveError && React.createElement("div", { className:"checkout-save-error", role:"alert" }, checkoutSaveError, React.createElement("button", { type:"button", onClick:()=>navigator.clipboard.writeText(checkoutOrderCode||'').catch(()=>{}), className:"checkout-save-copy" }, "Copiar código")),
'''+needle,1)
once('</style>\n\n<style id="v73-club-header-link">','''</style>
<style id="v102-reliable-orders">
.checkout-save-error{position:fixed;z-index:121;left:50%;transform:translateX(-50%);bottom:90px;width:min(94vw,470px);padding:12px;border-radius:15px;background:#3b1114;border:1px solid #b91c1c;color:#fff;font-size:12px;line-height:1.5;box-shadow:0 12px 30px rgba(0,0,0,.4)}.checkout-save-copy{display:block;margin-top:8px;padding:8px 12px;border-radius:10px;background:#7f1d1d;color:#fff;font-weight:800}.checkout-floating-cta:disabled{cursor:wait}.order-storage-warning{padding:12px;margin-bottom:12px;border-radius:14px;background:rgba(245,158,11,.12);border:1px solid rgba(245,158,11,.3);color:#fde68a;font-size:12px}
</style>

<style id="v73-club-header-link">''')
once('            adminMessage && React.createElement("div", { className: "mb-4 bg-emerald-600/15 border border-emerald-500/30 text-emerald-300 rounded-2xl px-4 py-3 text-sm" }, adminMessage),','            adminMessage && React.createElement("div", { className: "mb-4 bg-emerald-600/15 border border-emerald-500/30 text-emerald-300 rounded-2xl px-4 py-3 text-sm" }, adminMessage),\n            window.LA_ORDER_LOAD_WARNING && React.createElement("div", { className:"order-storage-warning", role:"alert" }, window.LA_ORDER_LOAD_WARNING),')
s=s.replace('const APP_VERSION = "v65-persistent-admin-photo-protection";', 'const APP_VERSION = "v102-reliable-orders";')
s=s.replace('<meta name="app-version" content="v95-print-orders-admin" />','<meta name="app-version" content="v102-reliable-orders" />')
p.write_text(s,encoding='utf-8')
print('v102 reliable order integration patched')